name: my_stocks
description: "My Stocks - Professional stock tracking app with real-time alerts and portfolio management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  # UI & Routing
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # Charts
  fl_chart: ^0.68.0

  # Network
  retrofit: ^4.4.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^6.0.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Background Tasks
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^17.2.3
  uuid: ^4.5.2
  http: ^1.2.2
  path_provider: ^2.1.5
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  rename_app: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1



flutter:
  uses-material-design: true
  assets:
    - assets/icon/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"